// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
const assert = require('assert')

describe('InsertSong', function () {
  this.timeout(30000)
  let driver: any
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('InsertSong', async function () {
    await driver.get("http://localhost:8100/")
    await driver.manage().window().setRect({ width: 1358, height: 821 })
    await driver.findElement(By.id("open-login")).click()
    await driver.sleep(500)
    await driver.findElement(By.id("ion-input-0")).click()
    await driver.findElement(By.id("ion-input-0")).sendKeys("dani@gmail.com")
    await driver.findElement(By.id("ion-input-1")).sendKeys("123456")
    await driver.findElement(By.css(".button-solid")).click()
    await driver.findElement(By.css(".fab-button-small > .md")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("open-modal"))), 30000)
    await driver.sleep(500)
    await driver.findElement(By.id("open-modal")).click()
    await driver.findElement(By.id("ion-input-2")).click()
    await driver.findElement(By.id("ion-input-2")).sendKeys("High")
    await driver.findElement(By.id("ion-input-3")).sendKeys("Maria Becerra")
    await driver.findElement(By.id("ion-input-4")).sendKeys("https://t2.genius.com/unsafe/340x340/https%3A%2F%2Fimages.genius.com%2Fda40d4e055decf93104948db3147d651.1000x1000x1.jpg")
    await driver.findElement(By.css(".ion-color-primary")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".back-button-has-icon-only")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("open-login"))), 30000)
    await driver.findElement(By.id("open-login")).click()
    await driver.sleep(500)
    await driver.findElement(By.css(".button-solid")).click()
  })
})
