// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import { environment } from 'src/environments/environment';
const assert = require('assert')

const dotenv = require('dotenv');

dotenv.config()

describe('Login Chrome', function () {
    this.timeout(30000)
    let driver: any;
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('Login', async function () {
        await driver.get(process.env['URL'])
        await driver.manage().window().setRect({ width: 1358, height: 821 })
        await driver.findElement(By.id("open-login")).click()
        await driver.sleep(500)
        await driver.findElement(By.id("ion-input-0")).click()
        await driver.findElement(By.id("ion-input-0")).sendKeys("dani@gmail.com")
        await driver.findElement(By.id("ion-input-1")).sendKeys("123456")
        await driver.findElement(By.css(".button-solid")).click()
        await driver.findElement(By.id("open-login")).click()
        await driver.sleep(500)
        await driver.findElement(By.css(".button-solid")).click()
    })
})


